name: fomo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  chopper: ^6.1.4
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  isar: 3.1.0
  isar_flutter_libs: 3.1.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: null
  chopper_generator: ^6.0.3
  custom_lint: null
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  isar_generator: 3.1.0
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
